### ISSUE TITLE
游戏客户端未启动，等待客户端启动

### ISSUE THREAD

**Issue by ByteInnoX** [Hanxven/League-Toolkit#2]
通过管理员启动也是连接不到，1.0.5和1.0.6-alpha.2版本都是这样

**Comment by Hanxven** [comment]
这段时间有事没法继续开发，等闲下来了就尝试解决。

**Comment by ByteInnoX** [comment]
好的，大佬 期待你的更新

**Comment by Hanxven** [comment]
想请您尝试一下这个版本，观察是否可正确连接。

[https://hanxven.lanzoum.com/i3RF31m](https://hanxven.lanzoum.com/i3RF31m) 58raj

**Comment by ByteInnoX** [comment]
好的 目前是没有问题 可以正常连接
